// default package
// Generated 23-lug-2020 18.21.24 by Hibernate Tools 5.3.0.Beta2
package restapi.rs;

import java.util.Date;

/**
 * Cluster generated by hbm2java
 */
public class ClusterInfo implements java.io.Serializable {

	
	private String customerClass;
	private String customerNo;
	
	private String techDescr;
	
	private String centro;
	
	private String status;
	
	private Date customer_activation_date;
	

	public Date getCustomer_activation_date() {
		return customer_activation_date;
	}

	public void setCustomer_activation_date(Date customer_activation_date) {
		this.customer_activation_date = customer_activation_date;
	}

	public ClusterInfo() {
	}

	public ClusterInfo(String customerNo) {
		this.customerNo = customerNo;
	}

	public ClusterInfo(String customerNo,  String customerClass, String techDescr, String centro,
			String status, Date customer_act_date) {
		this.customerNo = customerNo;
		this.customerClass = customerClass;
		this.techDescr = techDescr;
		this.centro = centro;
		this.status = status;
		this.customer_activation_date = customer_act_date;
		
	}

	public String getCustomerNo() {
		return this.customerNo;
	}

	public void setCustomerNo(String customerNo) {
		this.customerNo = customerNo;
	}

	
	public String getCustomerClass() {
		return this.customerClass;
	}

	public void setCustomerClass(String customerClass) {
		this.customerClass = customerClass;
	}


	

	public String getTechDescr() {
		return this.techDescr;
	}

	public void setTechDescr(String techDescr) {
		this.techDescr = techDescr;
	}

	

	
	public String getCentro() {
		return this.centro;
	}

	public void setCentro(String centro) {
		this.centro = centro;
	}

	

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

		

}
